# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0.0"
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v -c release
    - name: Upload release build
      uses: actions/upload-artifact@v4
      with:
        name: taylox-release
        path: |
          .build/release/taylox
          .build/release/taylox.dSYM
      
